# access point settings
ap_ssid=Guestbook
#ap_password=password

# captive portal settings
# see https://tools.ietf.org/html/rfc6762#appendix-G for private TLDs
portal_domain=guestbook.lan
portal_url=http://guestbook.lan/
